CREATE EXTENSION postgres_fdw;

DROP SERVER ms;
CREATE SERVER ms FOREIGN DATA WRAPPER postgres_fdw OPTIONS (host '192.168.1.177', dbname 'ms', port '5432');
GRANT USAGE ON FOREIGN SERVER ms TO _;

CREATE SCHEMA banks;
GRANT SELECT ON ALL TABLES IN SCHEMA banks TO _;
GRANT USAGE, CREATE ON SCHEMA banks TO _;

-- under db user _
CREATE USER MAPPING FOR _ SERVER ms OPTIONS (user 'ms', password '159753');
IMPORT FOREIGN SCHEMA banks FROM SERVER ms INTO banks;

